create table if not exists pupil (
    id integer generated by default as identity primary key,
    name varchar(100) not null,
    surname varchar(100) not null,
    lifecycle varchar(16) default 'ACTIVE' not null,
    constraint pupil_lifecycle_check check (lifecycle in ('ACTIVE', 'INACTIVE'))
);
