create table if not exists pupil (
    id integer generated by default as identity primary key,
    name varchar(100) not null,
    surname varchar(100) not null,
    lifecycle varchar(16) default 'ACTIVE' not null,
    constraint pupil_lifecycle_check check (lifecycle in ('ACTIVE', 'INACTIVE'))
);

create table if not exists course (
    id integer generated by default as identity primary key,
    school_class varchar(16) not null,
    subject varchar(32) not null,
    calendar_year integer not null,
    course_period varchar(16) not null,
    lifecycle varchar(16) default 'ACTIVE' not null,
    constraint course_school_class_check check (
        school_class in (
            'CLS_5A', 'CLS_5B', 'CLS_5C', 'CLS_5D', 'CLS_5E', 'CLS_5F',
            'CLS_6A', 'CLS_6B', 'CLS_6C', 'CLS_6D', 'CLS_6E', 'CLS_6F',
            'CLS_7A', 'CLS_7B', 'CLS_7C', 'CLS_7D', 'CLS_7E', 'CLS_7F',
            'CLS_8A', 'CLS_8B', 'CLS_8C', 'CLS_8D', 'CLS_8E', 'CLS_8F',
            'CLS_9A', 'CLS_9B', 'CLS_9C', 'CLS_9D', 'CLS_9E', 'CLS_9F',
            'CLS_10A', 'CLS_10B', 'CLS_10C', 'CLS_10D', 'CLS_10E', 'CLS_10F',
            'CLS_EF', 'CLS_Q1', 'CLS_Q2'
        )
    ),
    constraint course_subject_check check (subject in ('ENGLISH', 'SPANISH')),
    constraint course_calendar_year_check check (calendar_year between 1900 and 9998),
    constraint course_period_check check (course_period in ('FIRST_HALF', 'SECOND_HALF', 'FULL_YEAR')),
    constraint course_lifecycle_check check (lifecycle in ('ACTIVE', 'INACTIVE')),
    constraint course_unique unique (school_class, subject, calendar_year, course_period)
);

create table if not exists course_pupil (
    course_id integer not null,
    pupil_id integer not null,
    primary key (course_id, pupil_id),
    constraint course_pupil_course_fk foreign key (course_id) references course(id),
    constraint course_pupil_pupil_fk foreign key (pupil_id) references pupil(id)
);

create table if not exists exam (
    id integer generated by default as identity primary key,
    course_id integer not null,
    title varchar(100) not null,
    exam_date date not null,
    constraint exam_course_fk foreign key (course_id) references course(id),
    constraint exam_unique unique (course_id, title)
);
