spring.application.name=TopTeacher
server.port=8081
server.servlet.context-path=/top-teacher

spring.datasource.url=jdbc:h2:file:./data/topteacher;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:demo-data.sql
vaadin.launch-browser=false
vaadin.allowed-packages=com.vaadin,org.vaadin,dev.hilla,de.westarps.topteacher,de.westarps.vaadin

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
