create table if not exists pupil (
    id integer generated by default as identity primary key,
    name varchar(100) not null,
    surname varchar(100) not null,
    lifecycle varchar(16) default 'ACTIVE' not null,
    constraint pupil_lifecycle_check check (lifecycle in ('ACTIVE', 'INACTIVE'))
);

create table if not exists course (
    id integer generated by default as identity primary key,
    school_class varchar(16) not null,
    subject varchar(32) not null,
    calendar_year integer not null,
    course_period varchar(16) not null,
    lifecycle varchar(16) default 'ACTIVE' not null,
    constraint course_school_class_check check (
        school_class in (
            'CLS_5A', 'CLS_5B', 'CLS_5C', 'CLS_5D', 'CLS_5E', 'CLS_5F',
            'CLS_6A', 'CLS_6B', 'CLS_6C', 'CLS_6D', 'CLS_6E', 'CLS_6F',
            'CLS_7A', 'CLS_7B', 'CLS_7C', 'CLS_7D', 'CLS_7E', 'CLS_7F',
            'CLS_8A', 'CLS_8B', 'CLS_8C', 'CLS_8D', 'CLS_8E', 'CLS_8F',
            'CLS_9A', 'CLS_9B', 'CLS_9C', 'CLS_9D', 'CLS_9E', 'CLS_9F',
            'CLS_10A', 'CLS_10B', 'CLS_10C', 'CLS_10D', 'CLS_10E', 'CLS_10F',
            'CLS_EF', 'CLS_Q1', 'CLS_Q2'
        )
    ),
    constraint course_subject_check check (subject in ('ENGLISH', 'SPANISH')),
    constraint course_calendar_year_check check (calendar_year between 1900 and 9998),
    constraint course_period_check check (course_period in ('FIRST_HALF', 'SECOND_HALF', 'FULL_YEAR')),
    constraint course_lifecycle_check check (lifecycle in ('ACTIVE', 'INACTIVE')),
    constraint course_unique unique (school_class, subject, calendar_year, course_period)
);

create table if not exists course_pupil (
    course_id integer not null,
    pupil_id integer not null,
    primary key (course_id, pupil_id),
    constraint course_pupil_course_fk foreign key (course_id) references course(id),
    constraint course_pupil_pupil_fk foreign key (pupil_id) references pupil(id)
);

create table if not exists exam (
    id integer generated by default as identity primary key,
    course_id integer not null,
    title varchar(100) not null,
    exam_date date not null,
    constraint exam_course_fk foreign key (course_id) references course(id),
    constraint exam_unique unique (course_id, title)
);

create table if not exists eh_part (
    id integer generated by default as identity primary key,
    exam_id integer not null,
    title varchar(200) not null,
    sort_order integer not null,
    constraint eh_part_exam_fk foreign key (exam_id) references exam(id) on delete cascade,
    constraint eh_part_sort_order_check check (sort_order >= 0)
);

create table if not exists eh_category (
    id integer generated by default as identity primary key,
    part_id integer not null,
    title varchar(200) not null,
    description_markdown clob default '' not null,
    sort_order integer not null,
    constraint eh_category_part_fk foreign key (part_id) references eh_part(id) on delete cascade,
    constraint eh_category_sort_order_check check (sort_order >= 0)
);

create table if not exists eh_task (
    id integer generated by default as identity primary key,
    category_id integer not null,
    title varchar(200) not null,
    sort_order integer not null,
    constraint eh_task_category_fk foreign key (category_id) references eh_category(id) on delete cascade,
    constraint eh_task_sort_order_check check (sort_order >= 0)
);

create table if not exists eh_requirement (
    id integer generated by default as identity primary key,
    task_id integer not null,
    description_markdown clob default '' not null,
    max_points integer not null,
    bonus boolean default false not null,
    sort_order integer not null,
    constraint eh_requirement_task_fk foreign key (task_id) references eh_task(id) on delete cascade,
    constraint eh_requirement_max_points_check check (max_points >= 0),
    constraint eh_requirement_sort_order_check check (sort_order >= 0)
);

create table if not exists eh_criterion (
    id integer generated by default as identity primary key,
    requirement_id integer not null,
    criterion_key varchar(100) not null,
    label varchar(1000) not null,
    sort_order integer not null,
    active boolean default true not null,
    constraint eh_criterion_requirement_fk foreign key (requirement_id) references eh_requirement(id) on delete cascade,
    constraint eh_criterion_sort_order_check check (sort_order >= 0),
    constraint eh_criterion_unique unique (requirement_id, criterion_key)
);

create table if not exists eh_criterion_result (
    criterion_id integer not null,
    pupil_id integer not null,
    achieved boolean default false not null,
    primary key (criterion_id, pupil_id),
    constraint eh_criterion_result_criterion_fk foreign key (criterion_id) references eh_criterion(id) on delete cascade,
    constraint eh_criterion_result_pupil_fk foreign key (pupil_id) references pupil(id)
);

create table if not exists eh_requirement_result (
    requirement_id integer not null,
    pupil_id integer not null,
    points integer default 0 not null,
    primary key (requirement_id, pupil_id),
    constraint eh_requirement_result_requirement_fk foreign key (requirement_id) references eh_requirement(id) on delete cascade,
    constraint eh_requirement_result_pupil_fk foreign key (pupil_id) references pupil(id),
    constraint eh_requirement_result_points_check check (points >= 0)
);

create table if not exists exam_note_section (
    id integer generated by default as identity primary key,
    exam_id integer not null,
    title varchar(200) not null,
    description_markdown clob default '' not null,
    sort_order integer not null,
    constraint exam_note_section_exam_fk foreign key (exam_id) references exam(id) on delete cascade,
    constraint exam_note_section_sort_order_check check (sort_order >= 0)
);
